// Generated by gencpp from file warehousebot_stm32/robot_statusRequest.msg
// DO NOT EDIT!


#ifndef WAREHOUSEBOT_STM32_MESSAGE_ROBOT_STATUSREQUEST_H
#define WAREHOUSEBOT_STM32_MESSAGE_ROBOT_STATUSREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace warehousebot_stm32
{
template <class ContainerAllocator>
struct robot_statusRequest_
{
  typedef robot_statusRequest_<ContainerAllocator> Type;

  robot_statusRequest_()
    : robot_status(0)  {
    }
  robot_statusRequest_(const ContainerAllocator& _alloc)
    : robot_status(0)  {
  (void)_alloc;
    }



   typedef int8_t _robot_status_type;
  _robot_status_type robot_status;





  typedef boost::shared_ptr< ::warehousebot_stm32::robot_statusRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::warehousebot_stm32::robot_statusRequest_<ContainerAllocator> const> ConstPtr;

}; // struct robot_statusRequest_

typedef ::warehousebot_stm32::robot_statusRequest_<std::allocator<void> > robot_statusRequest;

typedef boost::shared_ptr< ::warehousebot_stm32::robot_statusRequest > robot_statusRequestPtr;
typedef boost::shared_ptr< ::warehousebot_stm32::robot_statusRequest const> robot_statusRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::warehousebot_stm32::robot_statusRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::warehousebot_stm32::robot_statusRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::warehousebot_stm32::robot_statusRequest_<ContainerAllocator1> & lhs, const ::warehousebot_stm32::robot_statusRequest_<ContainerAllocator2> & rhs)
{
  return lhs.robot_status == rhs.robot_status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::warehousebot_stm32::robot_statusRequest_<ContainerAllocator1> & lhs, const ::warehousebot_stm32::robot_statusRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace warehousebot_stm32

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::warehousebot_stm32::robot_statusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::warehousebot_stm32::robot_statusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::warehousebot_stm32::robot_statusRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::warehousebot_stm32::robot_statusRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::warehousebot_stm32::robot_statusRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::warehousebot_stm32::robot_statusRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::warehousebot_stm32::robot_statusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "baa09d58d1bc59bf491ce2ed99050bc0";
  }

  static const char* value(const ::warehousebot_stm32::robot_statusRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbaa09d58d1bc59bfULL;
  static const uint64_t static_value2 = 0x491ce2ed99050bc0ULL;
};

template<class ContainerAllocator>
struct DataType< ::warehousebot_stm32::robot_statusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "warehousebot_stm32/robot_statusRequest";
  }

  static const char* value(const ::warehousebot_stm32::robot_statusRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::warehousebot_stm32::robot_statusRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 robot_status\n"
;
  }

  static const char* value(const ::warehousebot_stm32::robot_statusRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::warehousebot_stm32::robot_statusRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.robot_status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_statusRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::warehousebot_stm32::robot_statusRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::warehousebot_stm32::robot_statusRequest_<ContainerAllocator>& v)
  {
    s << indent << "robot_status: ";
    Printer<int8_t>::stream(s, indent + "  ", v.robot_status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAREHOUSEBOT_STM32_MESSAGE_ROBOT_STATUSREQUEST_H
