// Generated by gencpp from file warehousebot_stm32/robot_status.msg
// DO NOT EDIT!


#ifndef WAREHOUSEBOT_STM32_MESSAGE_ROBOT_STATUS_H
#define WAREHOUSEBOT_STM32_MESSAGE_ROBOT_STATUS_H

#include <ros/service_traits.h>


#include <warehousebot_stm32/robot_statusRequest.h>
#include <warehousebot_stm32/robot_statusResponse.h>


namespace warehousebot_stm32
{

struct robot_status
{

typedef robot_statusRequest Request;
typedef robot_statusResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct robot_status
} // namespace warehousebot_stm32


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::warehousebot_stm32::robot_status > {
  static const char* value()
  {
    return "baa09d58d1bc59bf491ce2ed99050bc0";
  }

  static const char* value(const ::warehousebot_stm32::robot_status&) { return value(); }
};

template<>
struct DataType< ::warehousebot_stm32::robot_status > {
  static const char* value()
  {
    return "warehousebot_stm32/robot_status";
  }

  static const char* value(const ::warehousebot_stm32::robot_status&) { return value(); }
};


// service_traits::MD5Sum< ::warehousebot_stm32::robot_statusRequest> should match
// service_traits::MD5Sum< ::warehousebot_stm32::robot_status >
template<>
struct MD5Sum< ::warehousebot_stm32::robot_statusRequest>
{
  static const char* value()
  {
    return MD5Sum< ::warehousebot_stm32::robot_status >::value();
  }
  static const char* value(const ::warehousebot_stm32::robot_statusRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::warehousebot_stm32::robot_statusRequest> should match
// service_traits::DataType< ::warehousebot_stm32::robot_status >
template<>
struct DataType< ::warehousebot_stm32::robot_statusRequest>
{
  static const char* value()
  {
    return DataType< ::warehousebot_stm32::robot_status >::value();
  }
  static const char* value(const ::warehousebot_stm32::robot_statusRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::warehousebot_stm32::robot_statusResponse> should match
// service_traits::MD5Sum< ::warehousebot_stm32::robot_status >
template<>
struct MD5Sum< ::warehousebot_stm32::robot_statusResponse>
{
  static const char* value()
  {
    return MD5Sum< ::warehousebot_stm32::robot_status >::value();
  }
  static const char* value(const ::warehousebot_stm32::robot_statusResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::warehousebot_stm32::robot_statusResponse> should match
// service_traits::DataType< ::warehousebot_stm32::robot_status >
template<>
struct DataType< ::warehousebot_stm32::robot_statusResponse>
{
  static const char* value()
  {
    return DataType< ::warehousebot_stm32::robot_status >::value();
  }
  static const char* value(const ::warehousebot_stm32::robot_statusResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // WAREHOUSEBOT_STM32_MESSAGE_ROBOT_STATUS_H
