// Generated by gencpp from file warehousebot_stm32/robot_statusResponse.msg
// DO NOT EDIT!


#ifndef WAREHOUSEBOT_STM32_MESSAGE_ROBOT_STATUSRESPONSE_H
#define WAREHOUSEBOT_STM32_MESSAGE_ROBOT_STATUSRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace warehousebot_stm32
{
template <class ContainerAllocator>
struct robot_statusResponse_
{
  typedef robot_statusResponse_<ContainerAllocator> Type;

  robot_statusResponse_()
    {
    }
  robot_statusResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::warehousebot_stm32::robot_statusResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::warehousebot_stm32::robot_statusResponse_<ContainerAllocator> const> ConstPtr;

}; // struct robot_statusResponse_

typedef ::warehousebot_stm32::robot_statusResponse_<std::allocator<void> > robot_statusResponse;

typedef boost::shared_ptr< ::warehousebot_stm32::robot_statusResponse > robot_statusResponsePtr;
typedef boost::shared_ptr< ::warehousebot_stm32::robot_statusResponse const> robot_statusResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::warehousebot_stm32::robot_statusResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::warehousebot_stm32::robot_statusResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace warehousebot_stm32

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::warehousebot_stm32::robot_statusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::warehousebot_stm32::robot_statusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::warehousebot_stm32::robot_statusResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::warehousebot_stm32::robot_statusResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::warehousebot_stm32::robot_statusResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::warehousebot_stm32::robot_statusResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::warehousebot_stm32::robot_statusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::warehousebot_stm32::robot_statusResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::warehousebot_stm32::robot_statusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "warehousebot_stm32/robot_statusResponse";
  }

  static const char* value(const ::warehousebot_stm32::robot_statusResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::warehousebot_stm32::robot_statusResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::warehousebot_stm32::robot_statusResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::warehousebot_stm32::robot_statusResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct robot_statusResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::warehousebot_stm32::robot_statusResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::warehousebot_stm32::robot_statusResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // WAREHOUSEBOT_STM32_MESSAGE_ROBOT_STATUSRESPONSE_H
