// Generated by gencpp from file warehousebot_stm32/state.msg
// DO NOT EDIT!


#ifndef WAREHOUSEBOT_STM32_MESSAGE_STATE_H
#define WAREHOUSEBOT_STM32_MESSAGE_STATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace warehousebot_stm32
{
template <class ContainerAllocator>
struct state_
{
  typedef state_<ContainerAllocator> Type;

  state_()
    : state(0)  {
    }
  state_(const ContainerAllocator& _alloc)
    : state(0)  {
  (void)_alloc;
    }



   typedef int8_t _state_type;
  _state_type state;





  typedef boost::shared_ptr< ::warehousebot_stm32::state_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::warehousebot_stm32::state_<ContainerAllocator> const> ConstPtr;

}; // struct state_

typedef ::warehousebot_stm32::state_<std::allocator<void> > state;

typedef boost::shared_ptr< ::warehousebot_stm32::state > statePtr;
typedef boost::shared_ptr< ::warehousebot_stm32::state const> stateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::warehousebot_stm32::state_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::warehousebot_stm32::state_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::warehousebot_stm32::state_<ContainerAllocator1> & lhs, const ::warehousebot_stm32::state_<ContainerAllocator2> & rhs)
{
  return lhs.state == rhs.state;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::warehousebot_stm32::state_<ContainerAllocator1> & lhs, const ::warehousebot_stm32::state_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace warehousebot_stm32

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::warehousebot_stm32::state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::warehousebot_stm32::state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::warehousebot_stm32::state_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::warehousebot_stm32::state_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::warehousebot_stm32::state_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::warehousebot_stm32::state_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::warehousebot_stm32::state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "a33bed68685ae53bd39b0a9242210752";
  }

  static const char* value(const ::warehousebot_stm32::state_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xa33bed68685ae53bULL;
  static const uint64_t static_value2 = 0xd39b0a9242210752ULL;
};

template<class ContainerAllocator>
struct DataType< ::warehousebot_stm32::state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "warehousebot_stm32/state";
  }

  static const char* value(const ::warehousebot_stm32::state_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::warehousebot_stm32::state_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int8 state\n"
;
  }

  static const char* value(const ::warehousebot_stm32::state_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::warehousebot_stm32::state_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.state);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct state_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::warehousebot_stm32::state_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::warehousebot_stm32::state_<ContainerAllocator>& v)
  {
    s << indent << "state: ";
    Printer<int8_t>::stream(s, indent + "  ", v.state);
  }
};

} // namespace message_operations
} // namespace ros

#endif // WAREHOUSEBOT_STM32_MESSAGE_STATE_H
